Vagrant.configure(2) do |config|
   config.vm.box = "chad-thompson/ubuntu-trusty64-gui"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "4096"
     vb.name = "RefDistiller"
     #Disable USB
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
   end
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
    config.vm.provision "shell", inline: <<-SHELL
	# Install Java
	 sudo add-apt-repository ppa:webupd8team/java
	 sudo apt-get update -y
	 echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
	 sudo apt-get install -y oracle-java8-installer
	
	# Install wget utility
   	sudo apt-get install -y wget

	# Install unzip utility
   	sudo apt-get install -y unzip

	# Install git utility
 	sudo apt-get install -y git

	cd Desktop

	# install eclipse mars
  	wget http://mirror.cc.columbia.edu/pub/software/eclipse/technology/epp/downloads/release/mars/1/eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz

	#extract eclipse
   	tar xvzf eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz

  	cd eclipse/plugins

   	wget https://github.com/SoftwareEngineeringToolDemos/FSE-2014-RefDistiller/raw/master/Binary/refDistiller.tar.gz

	# install RefDistiller plugin
  	tar xvzf refDistiller.tar.gz

	# Install eclipse command line project import plugin 
   	wget ‐‐directory-prefix=/home/vagrant/Desktop/EclipseFiles/eclipse/plugins https://github.com/seeq12/eclipse-import-projects-plugin/raw/master/jar/com.seeq.eclipse.importprojects_1.3.0.jar

	cd ../../

	# Get Scripts from github repository
	git clone https://github.com/SoftwareEngineeringToolDemos/FSE-2014-RefDistiller.git

	cd FSE-2014-RefDistiller/build-vm
	sudo chmod +x commands.sh

	cp commands.sh ../../commands.sh
	cp RefDistiller.desktop ../../RefDistiller.desktop
	cp Readme.txt ../../Readme.txt
	cp -r Licenses/ ../../Licenses
	cp Installation.txt ../../Installation.txt	
	cp -r ../Binary/ ../../RefDistillerBinary/
	cp RefDistillerAuthorDemonstration.desktop ../../RefDistillerAuthorDemonstration.desktop
	cp RefDistillerDemoVideo.desktop ../../RefDistillerDemoVideo.desktop
	cp RefDistillerWorkspace.tar.gz ../../RefDistillerWorkspace.tar.gz

	cd ../../

	tar xvzf RefDistillerWorkspace.tar.gz

	sudo mkdir "/home/vagrant/.config/autostart"
	sudo cp RefDistiller.desktop /home/vagrant/.config/autostart/RefDistiller.desktop

	
	#Remove unused Launcher Applications
	sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"

	sudo reboot

   SHELL
end

